name: ex_causalinf_env
channels:
  - defaults
dependencies:
  - anyio=2.2.0=py39hecd8cb5_1
  - appnope=0.1.2=py39hecd8cb5_1001
  - argon2-cffi=20.1.0=py39h9ed2024_1
  - arrow-cpp=4.0.1=py39hf7c73f6_3
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - aws-c-common=0.4.57=hb1e8313_1
  - aws-c-event-stream=0.1.6=h23ab428_5
  - aws-checksums=0.1.9=hb1e8313_0
  - aws-sdk-cpp=1.8.185=he271ece_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - boost-cpp=1.73.0=h9ed2024_11
  - bottleneck=1.3.2=py39he3068b8_1
  - brotli=1.0.9=hb1e8313_2
  - brotlipy=0.7.0=py39h9ed2024_1003
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.17.1=h9ed2024_0
  - ca-certificates=2021.7.5=hecd8cb5_1
  - certifi=2021.5.30=py39hecd8cb5_0
  - cffi=1.14.5=py39h2125817_0
  - chardet=4.0.0=py39hecd8cb5_1003
  - cryptography=3.4.7=py39h2fd3fbb_0
  - cycler=0.10.0=py39hecd8cb5_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - double-conversion=3.1.5=haf313ee_1
  - entrypoints=0.3=py39hecd8cb5_0
  - freetype=2.10.4=ha233b18_0
  - gflags=2.2.2=h0a44026_0
  - glog=0.5.0=h23ab428_0
  - grpc-cpp=1.26.0=h044775b_0
  - icu=58.2=h0a44026_3
  - idna=2.10=pyhd3eb1b0_0
  - importlib-metadata=3.10.0=py39hecd8cb5_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - intel-openmp=2021.2.0=hecd8cb5_564
  - ipykernel=5.3.4=py39h01d92e1_0
  - ipython=7.22.0=py39h01d92e1_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.2=py39hecd8cb5_1
  - jinja2=3.0.1=pyhd3eb1b0_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=he5867d9_2
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=3.2.0=py_2
  - jupyter-packaging=0.7.12=pyhd3eb1b0_0
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py39hecd8cb5_0
  - jupyter_server=1.4.1=py39hecd8cb5_0
  - jupyterlab=3.0.14=pyhd3eb1b0_1
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.4.0=pyhd3eb1b0_0
  - kiwisolver=1.3.1=py39h23ab428_0
  - krb5=1.18.2=h75d18d8_0
  - lcms2=2.12=hf1fd2bf_0
  - libboost=1.73.0=hd4c2dcd_11
  - libcurl=7.71.1=h8a08a2b_1
  - libcxx=10.0.0=1
  - libedit=3.1.20210216=h9ed2024_1
  - libevent=2.1.8=hddc9c9b_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.11.2=hd9629dc_0
  - libsodium=1.0.18=h1de35cc_0
  - libssh2=1.9.0=ha12b0ac_1
  - libthrift=0.13.0=h054ceb0_6
  - libtiff=4.2.0=h87d7836_0
  - libwebp-base=1.2.0=h9ed2024_0
  - llvm-openmp=10.0.0=h28b9765_0
  - lz4-c=1.9.3=h23ab428_0
  - markupsafe=2.0.1=py39h9ed2024_0
  - matplotlib=3.3.4=py39hecd8cb5_0
  - matplotlib-base=3.3.4=py39h8b3ea08_0
  - mistune=0.8.4=py39h9ed2024_1000
  - mkl=2021.2.0=hecd8cb5_269
  - mkl-service=2.3.0=py39h9ed2024_1
  - mkl_fft=1.3.0=py39h4a7008c_2
  - mkl_random=1.2.1=py39hb2f4e1b_2
  - nbclassic=0.2.6=pyhd3eb1b0_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py39hecd8cb5_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.0=py39hecd8cb5_0
  - numexpr=2.7.3=py39h5873af2_1
  - numpy=1.20.2=py39h4b4dc7a_0
  - numpy-base=1.20.2=py39he0bd621_0
  - olefile=0.46=py_0
  - openssl=1.1.1k=h9ed2024_0
  - orc=1.6.7=h001ef8f_2
  - packaging=21.0=pyhd3eb1b0_0
  - pandas=1.2.5=py39h23ab428_0
  - pandocfilters=1.4.3=py39hecd8cb5_1
  - parso=0.7.0=py_0
  - patsy=0.5.1=py39hecd8cb5_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.2.0=py39h5270095_0
  - pip=21.1.3=py39hecd8cb5_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pyarrow=4.0.1=py39hdf3e9eb_3
  - pycparser=2.20=py_2
  - pygments=2.9.0=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyrsistent=0.18.0=py39h9ed2024_0
  - pysocks=1.7.1=py39hecd8cb5_0
  - python=3.9.5=h88f2d9e_3
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pyzmq=20.0.0=py39h23ab428_1
  - re2=2020.11.01=h23ab428_1
  - readline=8.1=h9ed2024_0
  - requests=2.25.1=pyhd3eb1b0_0
  - scikit-learn=0.24.2=py39hb2f4e1b_0
  - scipy=1.6.2=py39hd5f7400_1
  - seaborn=0.11.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py39hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_0
  - snappy=1.1.8=hb1e8313_0
  - sniffio=1.2.0=py39hecd8cb5_1
  - sqlite=3.36.0=hce871da_0
  - statsmodels=0.12.2=py39h9ed2024_0
  - terminado=0.9.4=py39hecd8cb5_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.1=py39h9ed2024_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - tzdata=2021a=h52ac0ba_0
  - uriparser=0.9.3=h0a44026_1
  - urllib3=1.26.6=pyhd3eb1b0_1
  - utf8proc=2.6.1=h9ed2024_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py39hecd8cb5_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.9=h322a384_0
prefix: /Users/lars/anaconda3/envs/ex_causalinf_env
